### ISSUE TITLE
Some components are const and some classes - is there a reason why??

### ISSUE THREAD

**Issue by genyded** [djhi/my-nutrition#10]
This is really just a question and I think the answer may be you are starting to migrate, but is there any real reason that most react component are const exports, but a few like Coachees,jsx are classe?

As far as I know it shouldn't really make any difference, but I just wanted to be sure before I create a bunch of classes and then find out there is a very valid reason why you used const exports.

Thanks!

**Comment by genyded** [comment]
Figured out this is because some are smart and some are not.

**Comment by djhi** [comment]
exactly :)
