### ISSUE TITLE
Unexpected token <

### ISSUE THREAD

**Issue by carapai** [djhi/my-nutrition#18]
When I try to run I only see the word loading in the we browser.
During the process of running this error appears.
ERROR in ./app/client/actions/app.js
Module not found: Error: Cannot resolve module 'react-intl/lib/locale-data' in /Users/carapai/Projects/my-nutrition/app/client/actions
What I am doing wrong?

**Comment by tokn136** [comment]
open the app.js file and adapt the path to 'react-intl/locale-data/'

**Comment by djhi** [comment]
Can you try with the latest version ? Also, what browser are you using ?

**Comment by carapai** [comment]
Thank you very much, the first option fixed the problem
