### ISSUE TITLE
--no-clobber doesn't seem to work on mac 

### ISSUE THREAD

**Issue by kevohagan** [djhi/my-nutrition#2]
so i just removed it :)

**Comment by djhi** [comment]
Can you try with `cp -n` on mac ?

**Comment by kevohagan** [comment]
Yep that seems to work :)

Btw this repo looks awesome!! Thanks for open sourcing it!  Any tips on
where to learn a bit about redux?

im looking at this for the time being
https://egghead.io/series/getting-started-with-redux

**Comment by djhi** [comment]
Thanks :) Glad you like it ! The egghead videos are great but you should read the redux documentation too. @gaearon did an amazing job on it. I'm still learning redux and trying to use it correctly ^^

**Comment by jptissot** [comment]
Yeah, thanks a lot for open sourcing this. I like how all concerns are seperated. I have been investigating / learning new technologies for my next app. This architecture looks promising.

**Comment by djhi** [comment]
My pleasure! If you have comments and/or suggestions to improve it, please do so. It could be great to create an npm package for some Meteor Redux middlewares

**Comment by jptissot** [comment]
Ouais, je me demandais si tu les as crée ou si ils existaient déjà quelque part ?

**Comment by djhi** [comment]
Keep the comments in english for the others please ;) I made them from scratch but I think there are better ways to handle the subscriptions. I've seen a comment from @jedwards1211 on [meteor forum](https://forums.meteor.com/t/meteor-webpack-es6-modules-hot-code-patching-fixes-load-order-more/9110/42?u=gildaspk) about a middleware and I would love to see how he did it.
