### ISSUE TITLE
Can a production build be done on Windows?

### ISSUE THREAD

**Issue by genyded** [djhi/my-nutrition#9]
Tried `make run-prod` and getting:

node ./bin/production.js
core-js@1.2.6 without ES6 number constructor is up to date
 40% 4/8 build modules[BABEL] Note: The code generator has deoptimised the styl
ng of "C:/Users/genyd/AppData/Local/.meteor/projects/redux-epapers/webpack/lib/
ore-js-no-number.js" as it exceeds the max of "100KB".
 69% 1396/1407 build modulesThe unused option is deprecated. Please use options
discardUnused instead.
The urls option is deprecated. Please use options.normalizeUrl instead.
The idents option is deprecated. Please use options.mergeIdents instead.
The idents option is deprecated. Please use options.reduceIdents instead.
 78% additional chunk assets
<--- Last few GCs --->

  114550 ms: Scavenge 1389.3 (1455.9) -> 1389.3 (1455.9) MB, 15.1 / 0 ms (+ 0.0
ms in 1 steps since last GC) [allocation failure] [incremental marking delaying
mark-sweep].
  115768 ms: Mark-sweep 1389.3 (1455.9) -> 1389.3 (1453.9) MB, 1207.1 / 0 ms (+
0.0 ms in 2 steps since start of marking, biggest step 0.0 ms) [last resort gc]

  116865 ms: Mark-sweep 1389.3 (1453.9) -> 1388.9 (1455.9) MB, 1102.2 / 0 ms [l
st resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000002A8BFE44A59 <JS Object>
    2: _serializeMappings(aka SourceMapGenerator_serializeMappings) [C:\Users\g
nyd\AppData\Local\.meteor\projects\redux-epapers\node_modules\uglify-js\node_mo
ules\source-map\lib\source-map-generator.js:~285] [pc=000001FFB347C6D3] (this=0
0000C9D65FEBD1 <a SourceMapGenerator with map 000000169AC3B0A9>)
    3: toJSON(aka SourceMapGenerator_toJSON) [C:\Users\genyd\AppData\Local\.met
or\project...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
 makefile:21: recipe for target 'run-prod' failed
make: *** [run-prod] Error 3

**Comment by djhi** [comment]
I haven't tested this on windows and won't be able to do so. Can't help you sorry

**Comment by genyded** [comment]
No worries - can work with dev build and port over
